# Generated by Django 5.0.2 on 2024-02-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
    ]
