# Generated by Django 5.0.2 on 2024-02-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0002_area_bitacora_estatusreporte_licencia_privilegio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='NumeroEquipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='Agregar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='Editar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='Eliminar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relbitacoralicencia',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
