# Generated by Django 5.0.2 on 2024-02-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0003_alter_bitacora_activo_alter_bitacora_numeroequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
