# Generated by Django 5.0.2 on 2024-02-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0004_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='relbitacoralicencia',
            name='FechaActualizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='relbitacoralicencia',
            name='FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='FechaCreacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FCreacion',
            field=models.DateTimeField(),
        ),
    ]
