# Generated by Django 5.0.2 on 2024-02-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0005_alter_bitacora_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='PrivilegioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios', to='BitaServices.privilegio'),
        ),
    ]
