# Generated by Django 5.0.2 on 2024-02-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0008_alter_usuario_privilegioid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='PrivilegioId',
            new_name='Privilegios',
        ),
    ]
