# Generated by Django 5.0.2 on 2024-02-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0009_rename_privilegioid_usuario_privilegios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='AreaId',
            new_name='Areas',
        ),
        migrations.RenameField(
            model_name='relbitacoralicencia',
            old_name='BitacoraId',
            new_name='Bitacoras',
        ),
        migrations.RenameField(
            model_name='relbitacoralicencia',
            old_name='LicenciaId',
            new_name='Licencias',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='BitacoraId',
            new_name='Bitacoras',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='EstatusReporteId',
            new_name='EstatusReportes',
        ),
    ]
