# Generated by Django 5.0.2 on 2024-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0011_rename_areas_bitacora_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
