# Generated by Django 5.0.2 on 2024-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitaServices', '0012_alter_bitacora_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='privilegio',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relbitacoralicencia',
            name='FechaActualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relbitacoralicencia',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
